# Create a Docker image that is ready to run the main Checker Framework tests,
# using OpenJDK 21.
# To convert this file to use a newer JDK, search (from the top level of the
# Checker Framework and Annotation Tools repositories) for: (java|jdk).?21\b

# "ubuntu" is the latest LTS release.  "ubuntu:rolling" is the latest release.
# As of 2023-11-15, "ubuntu:rolling" is still 23.04.
FROM ubuntu:23.10
MAINTAINER Werner Dietl <wdietl@gmail.com>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" and "apt cleanup" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -y install aptitude \
&& aptitude -y install \
  apt-utils

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& aptitude -y install \
  openjdk-17-jdk \
  openjdk-21-jdk

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& aptitude -y install \
  ant \
  binutils \
  build-essential \
  cpp \
  git \
  jq \
  libcurl3-gnutls \
  make \
  maven \
  pipx \
  python3-distutils \
  python3-requests \
  unzip \
  wget

# Maven 3.8.7 is the default on Ubuntu 23.04, so the below is not needed.
# (Don't try to use a variable here for the Maven version.)
# RUN export DEBIAN_FRONTEND=noninteractive \
# && wget https://mirrors.sonic.net/apache/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz \
# && tar xzvf apache-maven-3.9.5-bin.tar.gz
# ENV PATH="/apache-maven-3.9.5/bin:$PATH"

ENV PATH="/root/.local/bin:$PATH"
RUN pipx install --pip-args="--no-cache-dir" lithium-reducer

RUN mkdir /python-env \
&& python3 -m venv /python-env \
&& /python-env/bin/pip install --no-cache-dir lithium-reducer PyGithub pyyaml

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get autoremove \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
